#Configuration
doctrine:
  dbal:
    connections:
      example:
        driver:   "%db_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

  orm:
    entity_managers:
      example:
        connection: example
        mappings:
          ExampleAppBundle: ~